spring:
  datasource:
    url: jdbc:sqlite:bluetoothproximitydemoserver.db
  jpa:
    hibernate.ddl-auto: create
    open-in-view: true
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.id.new_generator_mappings: false
    show-sql: true
